easy_admin:
    design:
        brand_color: 'red'

    entities:
        Livre:
            # ...
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: /public/images/livres }
                    - { property: 'image', template: 'vich_uploader_image.html.twig' }
            # ...
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: /public/images/livres }
            
            form:
                fields:
                    # - { property: 'imageFile', type: 'file' }
                    - { property: 'imageFile', type: 'vich_image' }
            
         

